Navbar and footer
BrightCoders-Institute/proyecto-final-jdg pull request #12
Opened 2023-08-03 01:03 UTC by JoseLopezSolis

# What did we implement in this PR?

- We Implements the header and footer design.
- The design implemented is responsive for all devises.
- We implement real customer information.
## Screenshots
![image](https://github.com/BrightCoders-Institute/proyecto-final-jdg/assets/77039326/86d0da57-d16d-465f-bdad-d2e9bef66ac9)
![image](https://github.com/BrightCoders-Institute/proyecto-final-jdg/assets/77039326/cc9f4f4a-d3e6-44a3-a546-2abfb12bf129)

2023-08-03 03:12 UTC, JuanequeX requested changes
I'll recommend that the base language for this project are in English because this is one approach to work in `brightcoders`

2023-08-03 03:12 UTC, JuanequeX commented on app/assets/stylesheets/application.scss
> + }
- Add a space between the class and your curly brace
- remove the `!importants` totally is a bad practice used its.

2023-08-03 03:12 UTC, JuanequeX commented on app/assets/stylesheets/components/_top-message.scss
> +  background-color: var(--black-background) !important;
- sort alphabetically this block
- remove impotants
- add space in your class with the curly brace
- add a blank line at the end of this file

2023-08-03 03:12 UTC, JuanequeX commented on app/assets/stylesheets/config/variables.scss
> +  --black-background: #181818;
in scss the correct way to declare variables is with `$` like this:
- `$black-background: #181818;`

2023-08-03 03:12 UTC, JuanequeX commented on app/assets/stylesheets/layout/_footer.scss
> +  background-color: var(--black-background)!important;
the way to call your color in scss should be like this:
- `$black-background;`
- Remove the important.

2023-08-03 03:12 UTC, JuanequeX commented on app/assets/stylesheets/layout/_navbar.scss
> +  width: 9rem !important;
please remove the important

2023-08-03 03:12 UTC, JuanequeX commented on app/assets/stylesheets/layout/_navbar.scss
> +  cursor: pointer;
sort alphabetically

2023-08-03 03:12 UTC, JuanequeX commented on app/helpers/home_helper.rb
> +end
if this helper hasn't any propose in this feature please remove it.

2023-08-03 03:12 UTC, JuanequeX commented on app/views/partials/layout/_navbar.html.erb
> +      <%= image_tag("monkeyHats.jpg", class: "rounded-circle logo-size mx-auto") %>
totally is better use images in the `webp` format this bring a better performance in the SEO and in the `lighthouse` tests

2023-08-03 23:34 UTC, claunicole approved these changes

2023-08-08 00:38 UTC, JuanequeX approved these changes

2023-08-08 00:58 UTC, merged