Build home page
BrightCoders-Institute/proyecto-final-jdg pull request #33
Opened 2023-08-19 00:38 UTC by JoseLopezSolis

### Summary
This pull request introduces significant updates to our monkey hats e-commerce website. The changes include a refreshed home page design, enhanced product displays.

### Changes Made

1. **Home Page Styling**
   - Updated the home page with a playful and eye-catching jungle-inspired design.
   - Improved the overall layout for a more user-friendly experience.
   - Designed to create a visually appealing and engaging entry point for visitors.

2. **Product Display**
   - Curated a selection of our top-selling monkey hats for prominent display.
   - Highlighted key features of our products, including materials, sizes, and unique designs.
   - Emphasized the fun and warmth that our monkey hats bring to customers.

**Screenshots**
![image](https://github.com/BrightCoders-Institute/proyecto-final-jdg/assets/77039326/77dfd95c-3560-42e3-9f29-4207036f4e26)
![image](https://github.com/BrightCoders-Institute/proyecto-final-jdg/assets/77039326/cf6232b3-e78d-4ccf-88f6-b1752961f9e9)

![image](https://github.com/BrightCoders-Institute/proyecto-final-jdg/assets/77039326/71d97fd2-5419-4bbe-98ac-f2d90f4fff94)

2023-08-19 00:54 UTC, JuanequeX requested changes

2023-08-19 00:54 UTC, JuanequeX commented on app/assets/stylesheets/application.scss
> +  color: #fff;
Define a variable for this color.

2023-08-19 00:54 UTC, JuanequeX commented on app/assets/stylesheets/application.scss
> +  text-align: center;
sort alphabetically this lines

2023-08-19 00:54 UTC, JuanequeX commented on app/assets/stylesheets/application.scss
> +  color: #000000;
define a variable here too

2023-08-19 00:54 UTC, JuanequeX commented on app/assets/stylesheets/application.scss
> +  border: none;
sort it

2023-08-19 00:54 UTC, JuanequeX commented on app/assets/stylesheets/application.scss
> + // **END**//
add a blank line at the end of this file

2023-08-19 00:54 UTC, JuanequeX commented on app/views/devise/sessions/new.html.erb
>          </div>
delete the `<br>` and indented corrrectly

2023-08-19 00:54 UTC, JuanequeX commented on app/views/partials/Banners/_CoheteBanner.html.erb
> +</div>
indented correctly and add a blank line at the end

2023-08-19 00:54 UTC, JuanequeX commented on app/views/partials/Banners/_ElReyBanner.html.erb
> +</div>
indented correctly and add a blank line at the end

2023-08-19 00:54 UTC, JuanequeX commented on app/views/partials/Banners/_JuniorHBanner.html.erb
> +</div>
indented correctly and add a blank line at the end

2023-08-19 00:54 UTC, JuanequeX commented on app/views/partials/Banners/_ReyColoresBanner.html.erb
> +</div>
indented correctly and add a blank line at the end

2023-08-20 03:19 UTC, juperameza requested changes

2023-08-20 03:19 UTC, juperameza commented on app/views/devise/shared/_links.html.erb
> +      <%= link_to "Go to home", home_index_path, class: "text-orange" %><br />
Add a blank line at the end of this file

2023-08-20 03:19 UTC, juperameza commented on app/views/home/index.html.erb
> +<%= render partial: "partials/Products/products" %>
Add a blank line at the end of this file

2023-08-20 03:19 UTC, juperameza commented on app/views/partials/Banners/_FoodMoney.html.erb
> +</div>
Blank line

2023-08-20 03:19 UTC, juperameza commented on app/views/partials/Banners/_GranadaBanner.html.erb
> +</div>
BLank line

2023-08-20 03:19 UTC, juperameza commented on app/views/partials/Products/_products.html.erb
> +</div>
Add a blank line at the end here

2023-08-21 15:23 UTC, juperameza approved these changes
lgtm

2023-08-22 00:29 UTC, JuanequeX approved these changes

2023-08-22 18:02 UTC, merged