Product details
BrightCoders-Institute/proyecto-final-jdg pull request #43
Opened 2023-08-25 22:55 UTC by sr-meh

# Description 

## Issue [38](https://github.com/BrightCoders-Institute/proyecto-final-jdg/issues/38)

- Modify the way the products are displayed on the main page. Now the products stored in the database are displayed correctly.

- Add an 'Add to cart' button on the cards on the main page.

- Add styles to the product detail page.

- Adds a different view for admins and another view for customers on the product details page.

- Adds validation to allow both users with an active session and users without a session to view the product details.

## Screenshots

 ### Customer view

![image](https://github.com/BrightCoders-Institute/proyecto-final-jdg/assets/6729543/9a6c6a7d-c624-4776-8885-0fabd5c44d57)
![image](https://github.com/BrightCoders-Institute/proyecto-final-jdg/assets/6729543/568e99e7-d5b4-4a2a-879b-95edbcac665b)

### Admin view 
![image](https://github.com/BrightCoders-Institute/proyecto-final-jdg/assets/6729543/3ea97c32-ea14-44e7-a976-aa240fd63fa3)

2023-08-25 23:23 UTC, JuanequeX requested changes

2023-08-25 23:23 UTC, JuanequeX commented on app/assets/stylesheets/application.scss
> +}
```suggestion
.product {
  border: 1px solid #ddd;
  padding: 15px;
  text-align: center;

  img {
    height: 400px;
    max-width: 100%;
  }

  h2 {
    margin-top: 10px;
    font-size: 1.2em;
  }
}

```

2023-08-25 23:23 UTC, JuanequeX commented on app/controllers/application_controller.rb
> +
remove this line

2023-08-25 23:23 UTC, JuanequeX commented on app/controllers/products_controller.rb
remove these extra lines

2023-08-25 23:23 UTC, JuanequeX commented on app/views/products/show.html.erb
> +                  No Image
Enhancing the user experience involves adding a default system image rather than using plain text.

2023-09-11 21:25 UTC, PudinDeveloper approved these changes

2023-09-11 21:56 UTC, JuanequeX approved these changes

2023-09-11 23:49 UTC, juperameza approved these changes
Lgtm

2023-09-12 23:08 UTC, merged