Add Brands Table
BrightCoders-Institute/proyecto-final-jdg pull request #53
Opened 2023-08-31 01:15 UTC by Ballo1988

# Description

What did you implemented/Why did you implemented this:

- Added an API from Google that allows users to select their location and set their address in a more intiutive way
- all Address fields, but phone number, now autocompletes itself when selecting a location from the map
- Added Brands table, now admin can register brands and attach many images to it
- Modified Products, so now admin has to select a brand from already registered brand
- Modified Products, so they now can have many images.
- Modified Products form so now is more user friendly (now total price calculates itself!)
- Added some validations to prevent costumers from getting into trouble
random user emails and names.

## Screenshots
![image](https://github.com/BrightCoders-Institute/proyecto-final-jdg/assets/44328033/e942efce-c432-4b38-b9a5-211ddac8b543)
![image](https://github.com/BrightCoders-Institute/proyecto-final-jdg/assets/44328033/eb5d5116-23c3-4200-a1da-76c51ae0c6c0)
![image](https://github.com/BrightCoders-Institute/proyecto-final-jdg/assets/44328033/73bb0d3c-d941-4bbd-8926-0f568d3dc20e)
![image](https://github.com/BrightCoders-Institute/proyecto-final-jdg/assets/44328033/615048ac-4cc3-410a-ae73-1021b3587042)
![image](https://github.com/BrightCoders-Institute/proyecto-final-jdg/assets/44328033/676eb2f7-6094-4a8d-b65a-6a1e362b62f2)
![image](https://github.com/BrightCoders-Institute/proyecto-final-jdg/assets/44328033/06361169-4e5d-4821-8c8f-2f453386f7f1)
![image](https://github.com/BrightCoders-Institute/proyecto-final-jdg/assets/44328033/ffc1f773-1134-4ce5-8d05-0806fea395e4)
![image](https://github.com/BrightCoders-Institute/proyecto-final-jdg/assets/44328033/4cf969b5-5144-41f7-8dda-6da78fcb54a1)
![image](https://github.com/BrightCoders-Institute/proyecto-final-jdg/assets/44328033/8b415314-9fc0-4ab3-8add-80ed6b99b116)

Closes #46

2023-08-31 13:48 UTC, juperameza requested changes

2023-08-31 13:48 UTC, juperameza commented on app/views/addresses/_form.html.erb
> +</script>
You shouldnt do javascript like this. Use stimulus js controllers and add them to an element, you can also pass data back and forward. Heres a [video example](https://www.youtube.com/watch?v=nf88pbG1a6s) and [another one ](https://www.youtube.com/watch?v=pjYwjOShp0c) and a [blog ](https://dev.to/briankephart/passing-arguments-to-stimulusjs-controllers-1kgi)

2023-09-05 04:04 UTC, juperameza approved these changes
lgtm

2023-09-05 20:49 UTC, PudinDeveloper approved these changes
LGTM

2023-09-05 20:49 UTC, PudinDeveloper commented on test/models/brand_test.rb
> +  # end
Nothing important, just remove this extra lines.

2023-09-05 21:19 UTC, merged