Add icon user profile navbar
BrightCoders-Institute/proyecto-final-jdg pull request #56
Opened 2023-09-05 11:06 UTC by sr-meh

# ISSUE #40  Add Icon and User Profile View in Navigation Bar

# Description

This pull request adds a user profile feature to the application. Users can now view their address information and a list of their previous orders on their profile page.

# Changes Made

- Created a user profile view that displays the user's address information.
- Added a list of previous orders in the user profile view.
- Modified the necessary routes and controllers to support the user profile view.
- Fixed style errors in the mobile view of the address list.
- Modified the style of the address table to display correctly.
- Corrected the error of the delete addresses button. Now it functions correctly.
- Added order ID, order date, and order status fields to the order details view.

# How to test

- Log in as a user.
- Go to your profile by clicking on the user icon in the top right corner.
- Verify that address information is displayed correctly.
- Verify that the list of previous orders is displayed with basic details.
- Ensure that the links to previous orders are functional.

## Screenshots
###Desktop view
![image](https://github.com/BrightCoders-Institute/proyecto-final-jdg/assets/6729543/c0fdaf14-3d2a-4472-a94d-3d7eccb00fbe)

### Mobile view
![image](https://github.com/BrightCoders-Institute/proyecto-final-jdg/assets/6729543/21a3a341-0f9c-4950-b316-42d7e57b077a)

2023-09-05 16:11 UTC, juperameza requested changes

2023-09-05 16:11 UTC, juperameza commented on app/controllers/addresses_controller.rb
> +    render 'addresses/_index'
Use rails paths

2023-09-11 21:26 UTC, PudinDeveloper approved these changes
Same as @juperameza (nevermind, I saw you fixed it :D)

2023-09-11 23:48 UTC, juperameza approved these changes

2023-09-14 22:46 UTC, merged