Improve-home-page
BrightCoders-Institute/proyecto-final-jdg pull request #62
Opened 2023-09-14 14:25 UTC by sr-meh

# ISSUE #58 
# Description

- Enhanced Product Table Display: The pull request includes enhancements to the display of product tables for both mobile and desktop views.

- Button Styles: Button styles have been added to improve the overall appearance of buttons within the tables. This can make the interface more visually appealing and user-friendly.

- Codebase Cleanup: Duplicate partials have been removed from the codebase. This cleanup helps maintain code consistency and efficiency, making it easier to maintain and understand the code.

- Footer Links Correction: The links in the footer have been corrected to direct users to the respective "About Us" and "Frequently Asked Questions" views. This ensures that users can easily access important information.

- Image Placeholder: The "no image" text has been replaced with the appropriate image placeholder. This change improves the visual representation of products, even when images are not available.

- Additionally,  modify the home page index to show a banner corresponding to each of the registered brands and display the associated products for each of them.

## Screenshots

![image](https://github.com/BrightCoders-Institute/proyecto-final-jdg/assets/6729543/ab2ad083-395d-4980-86ba-09ab493a71c1)

2023-09-14 17:09 UTC, claunicole approved these changes

2023-09-14 17:13 UTC, JuanequeX requested changes

2023-09-14 17:13 UTC, JuanequeX commented on app/views/caps/index.html.erb
> +<%= render partial: "partials/Products/products" %>
For partials, the folder should be named `shared`

2023-09-14 17:13 UTC, JuanequeX commented on app/views/partials/Products/_brands.html.erb
> +      <% caps_products_by_brand = @caps_products.select { |product| product.brand == brand } %>
This logic should separated in the controller.

2023-09-14 17:13 UTC, JuanequeX commented on app/views/partials/Products/_brands.html.erb
> +      <% caps_products_by_brand = @caps_products.select { |product| product.brand == brand } %>
```suggestion
     def products_by_brand
         brand = params[:brand] # You can get the brand from a parameter, for example, if is necessary!!
         @caps_products_by_brand = @caps_products.select { |product| product.brand == brand }
    end
```

2023-09-14 17:13 UTC, JuanequeX commented on app/views/caps/index.html.erb
> +<%= render partial: "partials/Products/products" %>
and this same suggestion will be applied in each render partial!

2023-09-15 23:01 UTC, JuanequeX approved these changes

2023-09-15 23:04 UTC, merged