Show product
BrightCoders-Institute/proyecto-final-jdg pull request #64
Opened 2023-09-16 22:59 UTC by JoseLopezSolis

### Pull Request Description

**Objective:**  
This pull request introduces significant changes to the product display functionality across various pages of the application. The primary goal is to enhance the user experience by reorganizing how products are presented. Instead of a uniform product display, we have implemented specific views for each type of product. This redesign aims to make it easier for users to find the products they are looking for, improving overall usability.

**Screenshots**
![imagen](https://github.com/BrightCoders-Institute/proyecto-final-jdg/assets/77039326/4b869599-0ec3-4bd6-adc7-cfe73b454434)
![imagen](https://github.com/BrightCoders-Institute/proyecto-final-jdg/assets/77039326/8e28e175-98f4-4673-b191-20870ef5775a)
![imagen](https://github.com/BrightCoders-Institute/proyecto-final-jdg/assets/77039326/db4bbdf6-0c07-481a-8a57-2b0e9d56495e)
![imagen](https://github.com/BrightCoders-Institute/proyecto-final-jdg/assets/77039326/4c9b8ab2-d699-4247-9349-49fecb3e31bb)
![imagen](https://github.com/BrightCoders-Institute/proyecto-final-jdg/assets/77039326/c4f400c2-075e-438e-b3da-f05b04101c11)

Also Admin view were added to go different admin views.

2023-09-17 01:51 UTC, JuanequeX requested changes

2023-09-17 01:51 UTC, JuanequeX commented on app/assets/stylesheets/application.scss
> + "layout/navbar";
add a two-spaces indentation here.

2023-09-17 01:51 UTC, JuanequeX commented on app/assets/stylesheets/application.scss
> +
remove this unnecessary space

2023-09-17 01:51 UTC, JuanequeX commented on app/assets/stylesheets/application.scss
> +
remove this unnecessary space

2023-09-17 01:51 UTC, JuanequeX commented on app/assets/stylesheets/components/_cart.scss
> +}
Add a blank line at the end of this file

2023-09-17 01:51 UTC, JuanequeX commented on app/assets/stylesheets/components/_cart.scss
> +}
Add a space between the class name and the curly brace

2023-09-17 01:51 UTC, JuanequeX commented on app/assets/stylesheets/config/variables.scss
> +  $color-gray: #5a5a5a;
add a blank line at the end of this file

2023-09-17 01:51 UTC, JuanequeX commented on app/controllers/admin_view_controller.rb
> +  end
```suggestion
  def index; end
```

2023-09-17 01:51 UTC, JuanequeX commented on app/helpers/admin_view_helper.rb
> +end
if this helper is unnecessary please remove it

2023-09-17 01:51 UTC, JuanequeX commented on app/views/admin_view/index.html.erb
> +
remove this extra line

2023-09-17 01:51 UTC, JuanequeX commented on app/views/admin_view/index.html.erb
> +        <%= button_to "Brands", brands_path, :method => "get", class: "btn btn-dark w-100 h-50 py-4" %>
to avoid use the `:method => "get"` change for `link_to`

2023-09-17 01:51 UTC, JuanequeX commented on app/views/admin_view/index.html.erb
> +        <%= button_to "Products", products_path, :method => "get", class: "btn btn-dark w-100 py-4" %>
same here

2023-09-17 01:51 UTC, JuanequeX commented on app/views/admin_view/index.html.erb
> +        <%= button_to "Pending Orders", user_path(current_user), :method => "get", class: "btn btn-dark w-100 h-50 py-4" %>
same here

2023-09-17 01:51 UTC, JuanequeX commented on app/views/admin_view/index.html.erb
> +</div>
Add a blank line here

2023-09-17 01:51 UTC, JuanequeX commented on app/views/pins/index.html.erb
> +      <%= link_to product_path(product), class: "text-decoration-none text-black" do %>
indented correctly this line

2023-09-19 00:42 UTC, JuanequeX approved these changes

2023-09-19 16:36 UTC, claunicole approved these changes

2023-09-20 00:31 UTC, closed without merging